# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task : NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Install Node.js'

  - script: npm install --verbose
    displayName: 'Install dependencies'

  - script: npm run build --verbose
    displayName: 'Build Next.js app'
  
  - task: AzureStaticWebApp@0
    inputs:
      app_location: './'
      skip_api_build: true
      verbose: true
      azure_static_web_apps_api_token: '482347a12bc965871d970a4bb180348f4c2432d9f860de42ea25129400fbb9755-97d9cbea-19c3-4576-b255-afd78ba05ecb00f387275'
      cwd: '$(Pipeline.Workspace)'

#     steps:
#     - task: NodeTool@0
#       inputs:
#         versionSpec: "20.x"

#     - task: Npm@1
#       displayName: Npm Install
#       inputs:
#         command: install
#     - task: Npm@1
#       displayName: Npm Build
#       inputs:
#         command: 'custom'
#         customCommand: 'run build'
    
#     - task: ArchiveFiles@2
#       displayName: 'Archive Build Output'
#       inputs:
#         rootFolderOrFile: "."
#         includeRootFolder: false
#         archiveType: 'zip'
#         archiveFile: "$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip"
#         replaceExistingArchive: true

#     - task: PublishBuildArtifacts@1
#       displayName: Publish Artifacts
#       inputs:
#         pathToPublish: '$(Build.ArtifactStagingDirectory)'
#         artifactName: 'drop'

# - stage: Deploy
#   jobs:
#   - job: Deploy
#     displayName: "Deploy WebApp"
#     steps:
#     - task: DownloadBuildArtifacts@0
#       inputs:
#         buildType: 'current'
#         downloadType: 'single'
#         artifactName: 'drop'
#         downloadPath: '$(System.DefaultWorkingDirectory)'
#     - task: AzureRmWebAppDeployment@4
#       inputs:
#         ConnectionType: 'AzureRM'
#         azureSubscription: 'lls-tech Lembra Ai Subscription'
#         appType: 'webApp'
#         WebAppName: 'wa-lembra-ai-portal-dev'
#         packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'